Declare key/value format for PRODUCER in kafka file
jlandersen/vscode-kafka pull request #136
Opened 2021-03-17 16:21 UTC by angelozerr

Declare key/value format for PRODUCER in kafka file

Fixes #113

Signed-off-by: azerr azerr@redhat.com

2021-03-17 16:22 UTC, angelozerr commented
I need to write tests and doc but it should start to work.

2021-03-17 17:12 UTC, angelozerr commented
The PR can be reviewed now. There are tests and docs.

2021-03-18 09:20 UTC, fbricon requested changes

2021-03-18 09:20 UTC, fbricon commented on docs/Producing.md
> + * the rest of the content is the value upon `###` line is found.
until `###`

2021-03-18 09:20 UTC, fbricon commented on docs/Producing.md
> +Serializer can have the following value:
The serializers

2021-03-18 09:33 UTC, angelozerr commented on docs/Producing.md
> + * the rest of the content is the value upon `###` line is found.
fixed

2021-03-18 09:34 UTC, angelozerr commented on docs/Producing.md
> +Serializer can have the following value:
fixed

2021-03-18 15:48 UTC, fbricon requested changes

2021-03-18 15:48 UTC, fbricon commented on snippets/producers.json
> +            "PRODUCER ${1:keyed-message}",
${1:key-formatted-message}

2021-03-18 15:48 UTC, fbricon commented on snippets/producers.json
> +            "PRODUCER ${1:keyed-message}",
${1:formatted-message}

2021-03-19 06:08 UTC, angelozerr commented on snippets/producers.json
> +            "PRODUCER ${1:keyed-message}",
fixed

2021-03-19 06:08 UTC, angelozerr commented on snippets/producers.json
> +            "PRODUCER ${1:keyed-message}",
fixed

2021-03-19 09:59 UTC, merged

2021-03-19 10:00 UTC, fbricon commented
Thanks @angelozerr!