Use client accessor inside consumer
jlandersen/vscode-kafka pull request #139
Opened 2021-03-22 15:25 UTC by angelozerr

Use client accessor inside consumer

Fixes #138

Signed-off-by: azerr <azerr@redhat.com>

2021-04-14 16:09 UTC, angelozerr commented
@fbricon I think this PR is very important because it uses the pooling of kafka client https://github.com/jlandersen/vscode-kafka/pull/139/files#diff-f66af15c392b2023b98da968390a2eecdd539cbc17ac8ca4b23eb8db3e6de95fR103

The current version create a KafkaClient each time you start a consumer without dispose it!

2021-04-21 16:10 UTC, fbricon requested changes

2021-04-21 17:14 UTC, angelozerr commented on src/client/client.ts
> +    public consumer(config?: ConsumerConfig): any {
fixed.

2021-04-23 13:45 UTC, fbricon approved these changes

2021-04-23 14:48 UTC, merged