Validation support for properties kafka file
jlandersen/vscode-kafka pull request #159
Opened 2021-04-13 09:44 UTC by angelozerr

Validation support for properties kafka file

Fixes #152

Signed-off-by: azerr <azerr@redhat.com>

2021-04-14 12:53 UTC, angelozerr commented
Here a demo:

![DiagnosticsDemo2](https://user-images.githubusercontent.com/1932211/114713135-1ff46200-9d31-11eb-8a4b-7d4463644ed0.gif)

2021-04-14 15:11 UTC, fbricon commented
that looks really cool!

Small nitpick: the diagnostic range shouldn't include the leading space of the bad value

2021-04-14 15:14 UTC, angelozerr commented
> that looks really cool!

Glad it pleases you:)

> Small nitpick: the diagnostic range shouldn't include the leading space of the bad value

You are right, I must improve that.

2021-04-14 15:42 UTC, angelozerr commented
> Small nitpick: the diagnostic range shouldn't include the leading space of the bad value

Fixed!

2021-04-14 16:27 UTC, fbricon requested changes

2021-04-14 17:53 UTC, angelozerr commented on src/test/suite/kafka-file/languageservice/diagnosticsProperties.test.ts
> +
Yes sure I will implement it.

2021-04-14 18:42 UTC, angelozerr commented on docs/Consuming.md
> +Validation will help you to write valid kafka file.
fixed

2021-04-14 18:43 UTC, angelozerr commented on docs/Consuming.md
> +Here a sample with topic syntax:
fixed

2021-04-14 18:43 UTC, angelozerr commented on docs/Producing.md
> +Validation will help you to write valid kafka file.
fixed

2021-04-14 18:43 UTC, angelozerr commented on docs/Producing.md
> +Here a sample with producer which doesn't define the value:
fixed

2021-04-14 19:31 UTC, angelozerr commented on src/test/suite/kafka-file/languageservice/diagnosticsProperties.test.ts
> +
> can you test duplicate properties?

implemented (with test)

2021-04-15 14:10 UTC, merged

2021-04-15 14:10 UTC, fbricon commented
Thanks @angelozerr!